### ISSUE TITLE
Todos for 2017

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/SBC361-programming-in-R#15]
- [x] "intro" is something they should already know. Name it practical0. Keep regex as practical1
- [x] @EmelineAurore identified a few places with issues. Please identify them more clearly here and/or directly resolve them *BEFORE* other assistants work through the practicals
 - [ ] put our css on it.
 - [x] shift URLs to this year's verison

**Comment by EmelineAurore** [comment]
practical1 is now split into 2.

**Comment by EmelineAurore** [comment]
I do not understand "put our css on it" - can someone explain and make it happen?
