### ISSUE TITLE
practical 1: Confusion between logical and regular expressions

### ISSUE THREAD

**Issue by roddypr** [wurmlab/SBC361-programming-in-R#22]
"Q30. How many reptile names (genus or species) contain a lowercase "o" or an uppercase "E"?
Hint - you will have to combine your knowledge of regular expressions with your knowledge of logical expressions to answer this one!"

This could be asking students to use logical expression, although they have not been taught to use `grepl`:

```r
grepl("o", x) | grepl("E", x)
```

On the other hand, this could be asking students to use regular expression "alternation", which the practical does not explain, and which in my mind differs from traditional logical expressions:

 ```r
grep("(o|E)", x)  # Possibility 1
grep("[oE]", x)  # Possibility 2
```

**Comment by EmelineAurore** [comment]
I've added an extra hint for grep

**Comment by yannickwurm** [comment]
we do not want to use `grepl` and thus the comment about 'logical expression' is misleading. 
They will ahve seen `|` and `[]` in class
