### ISSUE TITLE
Practical 0

### ISSUE THREAD

**Issue by yeban** [wurmlab/SBC361-programming-in-R#23]
Broken formatting - 
![screen shot 2017-10-11 at 4 36 33 pm](https://user-images.githubusercontent.com/90373/31450867-7ca3d642-aea2-11e7-95d2-286dd7472420.png)

Possibly incomplete example - 
![screen shot 2017-10-11 at 4 45 23 pm](https://user-images.githubusercontent.com/90373/31451371-d3869570-aea3-11e7-92ac-aadd6d8bd026.png)

Possibly confusing -
![screen shot 2017-10-11 at 4 41 30 pm](https://user-images.githubusercontent.com/90373/31451189-61246a02-aea3-11e7-81a2-bb549c3c32ba.png)

**Comment by yeban** [comment]
I think the double brackets (`[[]]`) to access elements of a list access requires more explanation as well, but maybe that's covered in the courses. Double bracket is unusual in comparison to how vectors, matrices and data frames can be accessed using a single bracket. At first I thought it was a typo and students may not notice that using a single bracket returns 1 element list and not the actual object.

![screen shot 2017-10-11 at 4 48 07 pm](https://user-images.githubusercontent.com/90373/31451647-91392fb0-aea4-11e7-826d-3e34c27c82ca.png)

**Comment by EmelineAurore** [comment]
To do for next year's practical:

- [ ] fix formatting x <- false
- [ ] change level example
