### ISSUE TITLE
Prac2: function with multiple arguments

### ISSUE THREAD

**Issue by roddypr** [wurmlab/SBC361-programming-in-R#24]
Q3 (additional_hours) is confusing because it is asking from an arbitrary action (adding an arbitrary number of hours to the output of time_converter).

An alternative is to ask the students to create the reverse of `time_converter`:

```r
hours_to_seconds <- function(hours, minutes, seconds) {
  total_ hours <- hours + minutes/60 + seconds/3600
  return(total_ hours)
}
```

We could also update the name of `time_converter` to something more descriptive (e.g. `hours_minutes_seconds`).

**Comment by roddypr** [comment]
This would also be a more natural way for the next question, where we talk about default values in funciton arguments (make `hours_to_seconds` have `minutes=0` and `seconds=0` as defaults).

**Comment by roddypr** [comment]
and in the following question (miles per hour) could even take a distance in km, hours, minutes and seconds, and convert it to miles per hour.

**Comment by yannickwurm** [comment]
please go ahead with this suggestion

**Comment by roddypr** [comment]
done in b8c7af1 - but need someone to read through it before closing the issue

**Comment by EmelineAurore** [comment]
All fine, thank you both.
