### ISSUE TITLE
prac2 q1

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/SBC361-programming-in-R#25]
- [x] "before evaluating" the R code -> "before testing" 
- [x] q2 fields -> rows
- [x] q3: should be more complex. 
- [x] delete "The general construct of a"
- [x] rename "my_first_function" to something relevant
- [x] (don't worry too much about the computation in the middle) -> (`floor()` is R's built-in function function for rounding down to the closest whole number)
- [x] "run it on the numbers 5, 50000, and 10000000 seconds"  -> use relevant examples for testing (0, 3600, another)

**Comment by yannickwurm** [comment]
"Hopefully you can already see how functions can be useful. " --> "Functions can be very useful when you have to do the same calculation many times"

**Comment by yannickwurm** [comment]
"consumming" -> spelling

**Comment by yannickwurm** [comment]
q5 tests should include relevant ones (e.g. 0, 1m/s) where we know what answer to expect

**Comment by yannickwurm** [comment]
"use Google" --> "use an internet search engine"

**Comment by yannickwurm** [comment]
loop_values <- c(1:50)     - NO reason for c()

This intro to loops would benefit from fewer examples. Actually just delete the following:
## Non-sequential loop values
loop_values <- c(1:50)
for (value in loop_values) {
 	print(value)
}

## The same as writing:
for (value in 1:50) {
 	print(value)
}

**Comment by yannickwurm** [comment]
How about just using the word "index" instead of position?

**Comment by yannickwurm** [comment]
What's  -> what is

**Comment by yannickwurm** [comment]
the Example ## Sequential loop values
```my_favourite_numbers <- c(42, 3.14, 7, 69, 6.626e-34, 1024, 4, 2.718281828, 666 , 1.61803398, 99)
for (value in my_favourite_numbers) {
  print(paste(value, "is my favourite number"))
}
```

Would benefit by doing something addition. I suggest calculating (and displaying) the cumulative sum at each iteration

**Comment by yannickwurm** [comment]
for (practical_attribute in practical_attribute_vec) {  

Indentation is too big.  We should do the standard 4 spaces

**Comment by yannickwurm** [comment]
for (my_row in 1:5) {    <-- should use `1:number_of_rows`    (and add a line above to get `nrows(table)`

**Comment by EmelineAurore** [comment]
All suggestions have been applied here #c6991f0, except q5 one.

**Comment by EmelineAurore** [comment]
Q5 now includes testable distances (0 and 1) and time (0 and 8s). By the way, a bee's speed is in average 24km per hour.
