### ISSUE TITLE
Practical 2: missing bracket in 'Slightly more complex loops'

### ISSUE THREAD

**Issue by Nazrath10R** [wurmlab/SBC361-programming-in-R#27]
just need one at the arrow to close the 'print'

![sbc361-programming-in-r_practical2_md_at_master_ _wurmlab_sbc361-programming-in-r](https://user-images.githubusercontent.com/8961165/31780821-c18418d8-b4ee-11e7-9242-2076f2c6aa52.png)

**Comment by EmelineAurore** [comment]
Thank you! I have addressed this in this [commit](https://github.com/wurmlab/SBC361-programming-in-R/commit/2eece96731aaeef099dc601b0f782ee245a41f85).
