### ISSUE TITLE
Practical 2: nrow instead of nrows

### ISSUE THREAD

**Issue by Nazrath10R** [wurmlab/SBC361-programming-in-R#28]
Question 14 typo - first line of code

![screen shot 2017-10-19 at 19 11 26](https://user-images.githubusercontent.com/8961165/31786751-671e9734-b501-11e7-94c8-f7ed017d9bb3.png)

**Comment by EmelineAurore** [comment]
Thanks! I have addressed this in [this commit](https://github.com/wurmlab/SBC361-programming-in-R/commit/b2ab9b1f3a3a2abbd0edbf9e51e882c1a573ca62).
