### ISSUE TITLE
practical 2: webpage version does not have the ant table

### ISSUE THREAD

**Issue by EmelineAurore** [wurmlab/SBC361-programming-in-R#29]
I am not so sure why. @yeban would you know?

It should look like that (from md file):
<img width="939" alt="screen shot 2017-10-19 at 22 26 05" src="https://user-images.githubusercontent.com/9661216/31795122-87add3fa-b51c-11e7-8b01-ce42477f0dd3.png">

But it looks like that on the website:
<img width="943" alt="screen shot 2017-10-19 at 22 24 42" src="https://user-images.githubusercontent.com/9661216/31795091-70598366-b51c-11e7-80d5-2afa7ce1de10.png">

**Comment by yeban** [comment]
From website:

<img width="929" alt="screen shot 2017-10-20 at 9 46 02 am" src="https://user-images.githubusercontent.com/90373/31812640-8a3a87ee-b57b-11e7-9177-f1346c2d6ebe.png">

**Comment by EmelineAurore** [comment]
Thanks!
