### ISSUE TITLE
Question_31_32_Practical1 explanations

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/SBC361-programming-in-R#7]
I have made some changes/suggestions to Question_31_32_Practical1.md in 930592a97c398b60d246251809d9ad19dd7b23fe  However some work is still needed. This includes: 

- [x]  please reorder so that "x" is first, then repl, then pattern (as the pattern is the only thing changing it should be easy to see that that is the only thing changing)
- [x]  please test all of them (I wrote things from memory and so havnett tested any of them) - you may need to adjust so they work. 
- [x]  put the "two step" versions before the 1 step versions
- [x]  when creating a temp variable, subsequently delete it
- [x] rewrite the last one without the confusing \w and \s. Better to be more specific.  Similarly, don't use 'sub'. Finally, avoid "*" in favor of "+"

**Comment by lrsantiago** [comment]
I've done all changes according to your suggestions and some additional minor changes like:
Deleted unnecessary texts 
Rewrote the scripts to make them more readable.

**Comment by yannickwurm** [comment]
Reopening because there's more. And I've added more info/details that is approriate. 

- [ ] The lines beginning with: 
   first_part
   species_first_char
   last_part
are badlly oraganised because the thing that changes is in the middle. Please put the thing that chagnes at the end. to make for eay reading

- [ ] Use `tick tick tick R`  rather than `tick tick tick` to begin a section of code. That way github/markdown know how to color things. I've done this for some; please do this throughout. 
- [ ] Please do a spellcheck. 
- [ ] Please check for formatting. 
- [ ] Please doublecheck that everything works as expected.

**Comment by lrsantiago** [comment]
I finished. I'm gonna close this issue as soon as you aprove it. I have follow your suggestions and request and done additional things.
