### ISSUE TITLE
master and gh-pages out of sync

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/SBC361-programming-in-R#8]
Can this be automated? and a "simple" (github-equivalent) github theme be autoapplied? So we just direct studnets to e.g. http://wurmlab.github.io/SBC361-programming-in-R/Question_31_32_Practical1.html  ? thanks,
Yannick

**Comment by lrsantiago** [comment]
It is done. Ismail helped me with this and it is working well.

**Comment by yannickwurm** [comment]
Thanks -this looks good. However, a bunch of the code e.g. in https://wurmlab.github.io/SBC361-programming-in-R/practical2.html  is broken. @lrsantiago can you fix this for @jasminZ ? 

Thanks, yannick
